# Generated by Django 2.1.3 on 2019-06-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_authorities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authority',
            options={'verbose_name_plural': 'Authorities'},
        ),
    ]
